import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const APP="https://spendsense-seven.vercel.app";
const transactions=[["GROCERIES","Whole Foods","-$84.21"],["INCOME","Payroll deposit","+$3,240"],["DINING","Neighborhood cafe","-$18.40"]];

export default function SpendSense(){
 return <><Head><title>SpendSense — Your Financial Signal</title><meta name="description" content="AI financial intelligence that turns transactions into clarity."/><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;600;700;800&display=swap" rel="stylesheet"/></Head>
 <style jsx global>{`
 *{box-sizing:border-box}html{background:#03110f}body{margin:0;color:#ecfffb;background:#03110f;font-family:Manrope,sans-serif}a{color:inherit}.ss{min-height:100vh;overflow:hidden;background:radial-gradient(circle at 80% 10%,rgba(45,212,191,.15),transparent 30%),radial-gradient(circle,rgba(45,212,191,.06) 1px,transparent 1px) 0 0/24px 24px}
 nav{width:min(1320px,calc(100% - 48px));margin:auto;padding:22px 0;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid rgba(45,212,191,.15)}.brand{display:flex;align-items:center;gap:12px}.brand img{border-radius:13px}.brand strong{display:block}.mono{font:9px "DM Mono",monospace;letter-spacing:.13em;text-transform:uppercase;color:#67a9a0}.navlinks{display:flex;gap:12px;align-items:center}.navlinks a{text-decoration:none;font:10px "DM Mono",monospace;letter-spacing:.08em;text-transform:uppercase}.launch{padding:12px 16px;background:#2dd4bf;color:#03110f}
 .hero{width:min(1320px,calc(100% - 48px));margin:auto;padding:74px 0 90px;display:grid;grid-template-columns:.85fr 1.15fr;gap:70px;align-items:center}.hero h1{font-size:clamp(58px,7vw,105px);line-height:.88;letter-spacing:-.07em;margin:18px 0 25px}.hero h1 span{color:#2dd4bf}.hero p{max-width:560px;color:#80aaa5;line-height:1.75;font-size:16px}.actions{display:flex;gap:12px;margin-top:30px;flex-wrap:wrap}.actions a{padding:15px 20px;text-decoration:none;font:10px "DM Mono",monospace;letter-spacing:.1em;text-transform:uppercase}.actions .primary{background:#2dd4bf;color:#03110f}.actions .outline{border:1px solid rgba(45,212,191,.25)}
 .dashboard{position:relative;min-height:600px}.orbit{position:absolute;inset:2% 3%;border:1px solid rgba(45,212,191,.18);border-radius:50%;transform:rotate(-8deg)}.orbit:before,.orbit:after{content:"";position:absolute;width:16px;height:16px;background:#2dd4bf;border:5px solid #07302b;border-radius:50%;box-shadow:0 0 24px #2dd4bf}.orbit:before{top:10%;left:20%}.orbit:after{bottom:12%;right:16%}.dash-card{position:absolute;border:1px solid rgba(45,212,191,.18);background:rgba(5,29,26,.9);box-shadow:0 30px 80px rgba(0,0,0,.4);backdrop-filter:blur(12px)}.balance{top:9%;left:9%;width:64%;padding:28px}.balance small,.insight small{font:9px "DM Mono",monospace;letter-spacing:.12em;color:#65a69e}.balance h2{font-size:52px;margin:12px 0 22px}.bar{height:8px;background:#0a3934;border-radius:8px;overflow:hidden}.bar i{display:block;width:72%;height:100%;background:linear-gradient(90deg,#2dd4bf,#93fff0)}.spend-logo{position:absolute;right:0;top:0;width:210px;height:auto;border-radius:24%;filter:drop-shadow(0 22px 35px rgba(0,0,0,.45))}
 .activity{left:0;bottom:3%;width:68%;padding:22px}.tx{display:grid;grid-template-columns:80px 1fr auto;gap:10px;padding:13px 0;border-bottom:1px solid rgba(45,212,191,.1);font-size:12px}.tx:last-child{border:0}.tx b{color:#2dd4bf;font:8px "DM Mono",monospace}.tx span:last-child{font-family:"DM Mono",monospace}.insight{right:0;bottom:10%;width:38%;padding:22px;border-color:rgba(124,92,255,.32);background:rgba(20,13,45,.92)}.insight strong{display:block;font-size:18px;line-height:1.3;margin:12px 0}.insight p{font-size:11px;color:#a49abb;line-height:1.6}
 .bento{width:min(1320px,calc(100% - 48px));margin:auto;padding:90px 0;display:grid;grid-template-columns:1.25fr .75fr;gap:16px}.panel{border:1px solid rgba(45,212,191,.15);background:#061c19;padding:32px;min-height:300px}.panel h3{font-size:36px;letter-spacing:-.04em;margin:0 0 15px}.panel p{color:#80aaa5;line-height:1.7}.panel.ai{background:linear-gradient(145deg,#17102f,#091d1b);display:flex;flex-direction:column;justify-content:space-between}.question{padding:18px;border:1px solid rgba(167,139,250,.28);color:#d8d1ff;font:12px "DM Mono",monospace}.categories{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:35px}.cat{padding:18px;background:#082824}.cat b{display:block;color:#2dd4bf;font-size:22px;margin-bottom:6px}.cat span{color:#6d9b95;font-size:10px}
 footer{width:min(1320px,calc(100% - 48px));margin:auto;padding:30px 0;border-top:1px solid rgba(45,212,191,.14);display:flex;justify-content:space-between;color:#527e78;font:9px "DM Mono",monospace;text-transform:uppercase;letter-spacing:.1em}
 @media(max-width:850px){.hero{grid-template-columns:1fr}.dashboard{min-height:560px}.bento{grid-template-columns:1fr}}@media(max-width:520px){nav,.hero,.bento,footer{width:calc(100% - 28px)}.brand div{display:none}.hero{padding-top:55px}.hero h1{font-size:15vw}.dashboard{min-height:620px}.balance{width:90%;left:0}.spend-logo{width:145px}.activity{width:100%;bottom:0}.insight{width:64%;right:0;bottom:38%}.categories{grid-template-columns:1fr}.tx{grid-template-columns:65px 1fr auto}footer{flex-direction:column;gap:10px}}
 `}</style><main className="ss"><nav><div className="brand"><Image src="/logos/spendsense-brand-lockup-selected.png" alt="" width={44} height={44}/><div><strong>SpendSense</strong><span className="mono">Financial signal center</span></div></div><div className="navlinks"><Link href="/">Portfolio</Link><a className="launch" href={APP}>Open app ↗</a></div></nav>
 <section className="hero"><div><div className="mono">Your money · connected</div><h1>See the signal<br/><span>inside the spending.</span></h1><p>SpendSense is less like a budget spreadsheet and more like a living financial radar—connecting accounts, transactions, receipts, goals, and AI guidance in one place.</p><div className="actions"><a className="primary" href={APP}>Connect my finances ↗</a><a className="outline" href="#dashboard">Explore the signal</a></div></div>
 <div className="dashboard" id="dashboard"><div className="orbit"/><div className="dash-card balance"><small>TOTAL FINANCIAL PICTURE</small><h2>$12,480</h2><div className="bar"><i/></div></div><Image className="spend-logo" src="/logos/spendsense-brand-lockup-selected.png" alt="SpendSense logo" width={230} height={230}/><div className="dash-card activity"><span className="mono">Recent activity</span>{transactions.map(t=><div className="tx" key={t[1]}><b>{t[0]}</b><span>{t[1]}</span><span>{t[2]}</span></div>)}</div><div className="dash-card insight"><small>AI GUIDE</small><strong>Dining is trending 18% lower this month.</strong><p>You are on pace to move an extra $126 toward your savings goal.</p></div></div></section>
 <section className="bento"><div className="panel"><span className="mono">One connected picture</span><h3>Accounts, receipts, budgets, and goals finally speak the same language.</h3><p>Automatic categorization turns transaction noise into a financial model you can understand and act on.</p><div className="categories"><div className="cat"><b>72%</b><span>budget health</span></div><div className="cat"><b>4</b><span>accounts synced</span></div><div className="cat"><b>+$420</b><span>monthly opportunity</span></div></div></div><div className="panel ai"><div><span className="mono">Ask your own data</span><h3>Your AI finance guide knows the numbers.</h3></div><div className="question">“What changed in my spending this month?” →</div></div></section>
 <footer><span>SpendSense · AI financial intelligence</span><span>Connect · understand · plan · grow</span></footer></main></>}
